export const learningModules = [
  {
    id: 'intro-finance',
    title: 'Introduction to Finance',
    difficulty: 'Beginner',
    xp: 100,
    duration: '10 min',
    description: 'Understand money, income, needs vs wants, and why finance matters in everyday life.',
    level: 1,
    icon: '💰',
    badge: 'Foundation',
    day: 1,
    focus: 'Money basics',
  },
  {
    id: 'budgeting-basics',
    title: 'Budgeting Basics',
    difficulty: 'Beginner',
    xp: 120,
    duration: '12 min',
    description: 'Learn to plan spending, track expenses, and build a simple monthly budget.',
    level: 2,
    icon: '🧾',
    badge: 'Planner',
    day: 2,
    focus: 'Spend wisely',
  },
  {
    id: 'saving-money',
    title: 'Saving Money',
    difficulty: 'Beginner',
    xp: 140,
    duration: '14 min',
    description: 'Explore the 50/30/20 approach and create healthy saving habits.',
    level: 3,
    icon: '🏦',
    badge: 'Saver',
    day: 3,
    focus: 'Build a habit',
  },
  {
    id: 'emergency-fund',
    title: 'Emergency Fund',
    difficulty: 'Beginner',
    xp: 150,
    duration: '15 min',
    description: 'Create a safety net for unexpected expenses and job changes.',
    level: 4,
    icon: '🛟',
    badge: 'Prepared',
    day: 4,
    focus: 'Stay resilient',
  },
  {
    id: 'banking',
    title: 'Banking',
    difficulty: 'Beginner',
    xp: 160,
    duration: '16 min',
    description: 'Understand savings accounts, fixed deposits, debit cards, and bank statements.',
    level: 5,
    icon: '🏛️',
    badge: 'Banker',
    day: 5,
    focus: 'Know your account',
  },
  {
    id: 'digital-payments',
    title: 'Digital Payments',
    difficulty: 'Intermediate',
    xp: 180,
    duration: '18 min',
    description: 'Learn how UPI, wallets, and online payments work securely.',
    level: 6,
    icon: '📱',
    badge: 'Digital',
    day: 6,
    focus: 'Pay safely',
  },
  {
    id: 'credit-score',
    title: 'Credit Score',
    difficulty: 'Intermediate',
    xp: 190,
    duration: '18 min',
    description: 'Discover how credit reports shape your future borrowing power.',
    level: 7,
    icon: '📈',
    badge: 'Trusted',
    day: 7,
    focus: 'Build trust',
  },
  {
    id: 'loans',
    title: 'Loans',
    difficulty: 'Intermediate',
    xp: 200,
    duration: '20 min',
    description: 'Compare personal loans, EMIs, and smart borrowing decisions.',
    level: 8,
    icon: '💳',
    badge: 'Borrower',
    day: 8,
    focus: 'Borrow carefully',
  },
  {
    id: 'insurance',
    title: 'Insurance',
    difficulty: 'Intermediate',
    xp: 210,
    duration: '20 min',
    description: 'Get familiar with health, life, and motor insurance essentials.',
    level: 9,
    icon: '🛡️',
    badge: 'Protected',
    day: 9,
    focus: 'Stay protected',
  },
  {
    id: 'investing-basics',
    title: 'Investing Basics',
    difficulty: 'Intermediate',
    xp: 220,
    duration: '22 min',
    description: 'Interpret risk, return, and the basic building blocks of wealth creation.',
    level: 10,
    icon: '📊',
    badge: 'Investor',
    day: 10,
    focus: 'Grow money',
  },
  {
    id: 'mutual-funds',
    title: 'Mutual Funds',
    difficulty: 'Intermediate',
    xp: 230,
    duration: '22 min',
    description: 'See how diversified mutual funds can match different financial goals.',
    level: 11,
    icon: '🧠',
    badge: 'Diversified',
    day: 11,
    focus: 'Diversify smartly',
  },
  {
    id: 'stock-market',
    title: 'Stock Market',
    difficulty: 'Advanced',
    xp: 240,
    duration: '25 min',
    description: 'Understand market terms, indices, and how to think about long-term investing.',
    level: 12,
    icon: '📉',
    badge: 'Market',
    day: 12,
    focus: 'Read the market',
  },
  {
    id: 'taxes',
    title: 'Taxes',
    difficulty: 'Advanced',
    xp: 250,
    duration: '25 min',
    description: 'Learn taxes, deductions, returns, and the importance of planning.',
    level: 13,
    icon: '🧾',
    badge: 'Taxwise',
    day: 13,
    focus: 'Plan taxes',
  },
  {
    id: 'retirement-planning',
    title: 'Retirement Planning',
    difficulty: 'Advanced',
    xp: 260,
    duration: '28 min',
    description: 'Build a long-term retirement strategy with pension and savings options.',
    level: 14,
    icon: '🌅',
    badge: 'Future',
    day: 14,
    focus: 'Retire strong',
  },
  {
    id: 'financial-freedom',
    title: 'Financial Freedom',
    difficulty: 'Advanced',
    xp: 300,
    duration: '30 min',
    description: 'Tie everything together into a roadmap for independence and wealth building.',
    level: 15,
    icon: '🚀',
    badge: 'Freedom',
    day: 15,
    focus: 'Own your future',
  },
];

export const defaultLearningProgress = {
  completedModules: [],
  currentModuleId: learningModules[0].id,
  xp: 0,
  coins: 0,
  streak: 3,
  badges: ['First Steps'],
};
